# -*- Makefile -*-

src    = TLStream.fs
deps   = ../bin/CoreCrypto.dll ../bin/TLSLib.dll
target = ../bin/TLSStream.dll

.PHONY: all dist

all: $(target)

dist:
	cp $(src) $(distdir)

$(target): $(src) $(deps)
	$(fsc) $(fsflags) $(addprefix -r ,$(deps)) -a -o $@ $(src)

include ../Makefile.config
