# -*- Makefile -*-

# --------------------------------------------------------------------
TOP       = $(dir $(lastword $(filter %/Makefile.config,$(MAKEFILE_LIST))))
arch      = $(shell uname)
buildtype =

ifneq ($(findstring CYGWIN,$(arch)),)
buildtype = cygwin
else
buildtype = unix
endif

include $(TOP)/Makefile.config.$(buildtype)

# --------------------------------------------------------------------
fslibs  = \
	FSharp.PowerPack.dll \
	FSharp.PowerPack.Compatibility.dll \
	System.Xml.dll \
	System.Security.dll

csflags = /nologo /lib:../bin
fsflags = -d fs --debug+ --optimize- --tailcalls- --crossoptimize- --mlcompatibility -I ../bin $(addprefix -r ,$(fslibs)) --nologo
