include ../Makefile.inc

localfiles = Makefile
src = 
deps = 
target = 

.PHONY: all build dist clean

all: dist

build:

clean: clean-def

dist:
	@echo "TODO"

include ../Makefile_default.inc