# -*- Makefile -*-

src    := OpenSSL.cs
deps   := ../bin/BouncyCastle.Crypto.dll
target  = ../bin/OpenSSL.dll

include ../Makefile.config

.PHONY: all dist make.in

all: $(target)

dist:
	cp $(src) $(distdir)

make.in:
	@true

$(target): $(src) $(deps)
	$(csc) $(csflags) -unsafe $(addprefix -r:,$(deps)) -t:library -out:$@ $(src)
