# -*- Makefile -*-

src    := OpenSSL.cs
deps   := ../bin/BouncyCastle.Crypto.dll
target  = ../bin/OpenSSL.dll

include ../Makefile.config

.PHONY: all dist make.in

all: $(target)

dist:
	cp Makefile.config $(src) $(distdir)

make.in:
	@true

Makefile.config: CoreCrypto.fsproj
	-if [ -f $< ]; then ../scripts/makegen -o $@ $<; fi

CoreCrypto.fsproj:

$(target): $(src) $(deps)
	$(csc) $(csflags) -unsafe $(addprefix -r:,$(deps)) -t:library -out:$@ $(src)
