# -*- Makefile -*-

src    :=
deps   :=
target  = ../bin/Platform.dll

include ../Makefile.config

.PHONY: all dist make.in

all: $(target)

dist:
	cp Makefile.config $(src) $(distdir)

make.in: Makefile.config
	@true

Makefile.config: Platform.fsproj
	-if [ -f $< ]; then ../scripts/makegen -o $@ $<; fi

Platform.fsproj:

include Makefile.config

$(target): $(src) $(deps)
	$(fsc) $(fsflags) $(addprefix -r ,$(deps)) -a -o $@ $(src)
