# -*- Makefile -*-

src    :=
deps   := ../bin/BouncyCastle.dll
target  = ../bin/CoreCrypto.dll

include ../Makefile.config

.PHONY: all dist

all: $(target)

dist:
	cp Makefile.config $(src) $(distdir)

$(target): $(src) $(deps)
	$(fsc) $(fsflags) $(addprefix -r ,$(deps)) -a -o $@ $(src)

Makefile.config: CoreCrypto.fsproj
	-../makegen -o $@ $<

include Makefile.config
