#!/bin/bash

acc=""

for file in $@ ; do
	echo -n "$file.tc7: \$(libperv) \$(libfs7) "
	for dep in $acc ; do
		echo -n "$dep.fs7 "
	done
	echo "$file.fs7 $file.fs"
	echo -n -e "\t \$(f7t) -scripts $file "
	for dep in $acc ; do
		echo -n "$dep.fs7 "
	done
	echo -n "$file.fs7 $file.fs"
	# echo -n " | tee $file.tc7" # Currently disabled, as tee is suppressing output on some platforms
	echo "" ; echo ""
	acc="$acc $file"
done