# -*- Makefile -*-

src    :=
deps   := ../bin/BouncyCastle.dll ../bin/CoreCrypto.dll
target  = ../bin/TLSLib.dll

include ../Makefile.config

.PHONY: all dist make.in

all: $(target)

dist:
	cp Makefile.config $(src) $(distdir)

make.in: Makefile.config
	@true

$(target): $(src) $(deps)
	$(fsc) $(fsflags) --warn:0 $(addprefix -r ,$(deps)) -a -o $@ $(src)

Makefile.config: lib.fsproj
	if [ -f $< ]; then ../makegen -o $@ $<; fi

lib.fsproj:

include Makefile.config
