# -*- Makefile -*-

src    :=
deps   := ../bin/BouncyCastle.Crypto.dll ../bin/CoreCrypto.dll ../bin/DB.dll
target  = ../bin/TLSLib.dll

include ../Makefile.config

.PHONY: all dist make.in

all: $(target)

dist:
	cp Makefile.config $(src) $(distdir)

make.in: Makefile.config
	@true

Makefile.config: lib.fsproj
	if [ -f $< ]; then ../makegen -o $@ $<; fi

lib.fsproj:

include Makefile.config

$(target): $(src) $(deps)
	$(fsc) $(fsflags) --warn:0 $(addprefix -r ,$(deps)) -a -o $@ $(src)
