# -*- Makefile -*-

# --------------------------------------------------------------------
include ../Makefile.config

target = ../bin/BouncyCastle.dll

# --------------------------------------------------------------------
.PHONY: all dist

all: $(target)

dist:
	find bzip2 src -type d -exec mkdir '$(distdir)/{}' ';'
	find bzip2 src -type f -print0 | \
		xargs -0 -I '{}' -- cp --parent '{}' '$(distdir)'

$(target): $(srcs)
	$(csc) $(csflags) /target:library /out:$@ /recurse:*.cs
