# -*- Makefile -*-

# --------------------------------------------------------------------
include ../Makefile.config

target = ../bin/BouncyCastle.dll

# --------------------------------------------------------------------
.PHONY: all dist

all: $(target)

dist:
	find bzip2 src -type f -name '*.cs' -print0 | \
		tar --null -T - -cf - | \
		tar -C '$(distdir)' -xof -

$(target): $(srcs)
	$(csc) $(csflags) /target:library /out:$@ /recurse:*.cs
