# -*- Makefile -*-

src    = \
	EchoServer.fsi \
	EchoServer.fs  \
	EchoTest.fs

deps   = ../bin/CoreCrypto.dll ../bin/TLSLib.dll ../bin/TLSStream.dll
target = ../bin/EchoServer.exe

.PHONY: all dist

all: $(target)

dist:
	cp $(src) $(distdir)

$(target): $(src) $(deps)
	$(fsc) $(fsflags) $(addprefix -r ,$(deps)) -o $@ $(src)

include ../Makefile.config
